import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useChainId } from "wagmi";
import {
  Gavel,
  AlertCircle,
  FileText,
  CheckCircle,
  Scale,
  ShieldAlert,
} from "lucide-react";
import { Button, AddressDisplay, Spinner } from "@settleone/design-system";
import { useGetDeal, useGetDispute, useResolveDispute } from "@settleone/sdk";
import { formatAmount } from "@settleone/utils";

export function DisputeDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const chainId = useChainId();
  const dealId = id ? BigInt(id) : undefined;

  const [status, setStatus] = useState<
    "idle" | "submitting" | "success" | "error"
  >("idle");
  const [resolutionNote, setResolutionHash] = useState("");

  const { data: deal, isLoading: isDealLoading } = useGetDeal(chainId, dealId);
  const { data: dispute, isLoading: isDisputeLoading } = useGetDispute(
    chainId,
    dealId,
  );
  const { resolveDispute } = useResolveDispute(chainId);

  const handleResolve = async (outcome: number) => {
    if (!dealId) return;
    try {
      setStatus("submitting");

      // Map outcome to BPS (Basis Points)
      let sellerBps = 0n;
      let buyerBps = 0n;

      if (outcome === 1) {
        // Seller Wins
        sellerBps = 10000n;
        buyerBps = 0n;
      } else if (outcome === 2) {
        // Buyer Wins
        sellerBps = 0n;
        buyerBps = 10000n;
      } else {
        // Split 50/50
        sellerBps = 5000n;
        buyerBps = 5000n;
      }

      // Mock resolution hash
      const resolutionHash =
        "0x1234567890123456789012345678901234567890123456789012345678901234";

      await resolveDispute(
        dealId,
        outcome,
        sellerBps,
        buyerBps,
        resolutionHash,
      );
      setStatus("success");
    } catch (err) {
      console.error("Resolution failed", err);
      setStatus("error");
    }
  };

  if (isDealLoading || isDisputeLoading) {
    return (
      <div className="flex justify-center py-20">
        <Spinner size="lg" />
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto py-8 px-4">
      <div className="flex items-center justify-between mb-8">
        <div>
          <button
            onClick={() => navigate("/disputes")}
            className="text-sm text-gray-500 hover:text-gray-900 mb-2 flex items-center gap-1"
          >
            ← Back to Queue
          </button>
          <h1 className="text-2xl font-bold text-gray-900 flex items-center gap-3">
            Review Dispute: #DL-{String(dealId).padStart(5, "0")}
            <span className="text-xs bg-red-100 text-red-600 px-2 py-0.5 rounded-full uppercase tracking-wider">
              ACTIVE
            </span>
          </h1>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Case Info */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white border border-[var(--border)] rounded-xl shadow-sm p-6">
            <h3 className="font-bold text-gray-900 mb-4 flex items-center gap-2">
              <FileText size={18} className="text-gray-400" /> Evidence &
              Context
            </h3>
            <div className="space-y-4">
              <div className="p-4 bg-gray-50 rounded-md border border-gray-100">
                <p className="text-xs font-semibold text-gray-400 uppercase mb-2">
                  Claimant Message
                </p>
                <p className="text-sm text-gray-700">
                  "The seller submitted a report that is 80% generated by AI and
                  contains multiple factual errors regarding our specific
                  contract logic. This does not meet the 'High Fidelity Manual
                  Review' requirement in the deal terms."
                </p>
              </div>
              <div className="flex items-center justify-between p-3 border border-gray-200 rounded-md">
                <div className="flex items-center gap-3">
                  <FileText className="text-red-500" size={20} />
                  <div>
                    <p className="text-sm font-medium">Terms_And_Specs.pdf</p>
                    <p className="text-[10px] text-gray-400 font-mono">
                      {deal?.metadataHash}
                    </p>
                  </div>
                </div>
                <Button variant="ghost" size="sm">
                  View CID
                </Button>
              </div>
            </div>
          </div>

          <div className="bg-white border border-[var(--border)] rounded-xl shadow-sm p-6">
            <h3 className="font-bold text-gray-900 mb-4">Resolution Note</h3>
            <textarea
              value={resolutionNote}
              onChange={(e) => setResolutionHash(e.target.value)}
              className="w-full h-32 p-3 border border-gray-200 rounded-md text-sm focus:ring-2 focus:ring-blue-500"
              placeholder="Provide a detailed explanation for your verdict. This will be visible to both parties."
            />
          </div>
        </div>

        {/* Right: Actions */}
        <div className="space-y-6">
          <div className="bg-white border border-[var(--border)] rounded-xl shadow-sm p-6">
            <h3 className="font-bold text-gray-900 mb-4">Verdict Center</h3>
            <p className="text-xs text-gray-500 mb-6">
              Choose an outcome. This will trigger the settlement logic and
              distribute the {deal ? formatAmount(deal.amount, 6) : "0"} USDC
              held in vault.
            </p>

            {status === "success" ? (
              <div className="text-center py-4">
                <CheckCircle
                  size={40}
                  className="text-green-500 mx-auto mb-2"
                />
                <p className="text-sm font-bold text-gray-900">Case Resolved</p>
                <Button
                  variant="ghost"
                  onClick={() => navigate("/disputes")}
                  className="mt-4"
                >
                  Back to Queue
                </Button>
              </div>
            ) : (
              <div className="space-y-3">
                <Button
                  onClick={() => handleResolve(2)}
                  disabled={status === "submitting"}
                  className="w-full bg-red-600 hover:bg-red-700 justify-start"
                >
                  <ShieldAlert size={16} className="mr-2" /> Refund Buyer (100%)
                </Button>
                <Button
                  onClick={() => handleResolve(1)}
                  disabled={status === "submitting"}
                  className="w-full bg-green-600 hover:bg-green-700 justify-start"
                >
                  <CheckCircle size={16} className="mr-2" /> Release to Seller
                  (100%)
                </Button>
                <Button
                  onClick={() => handleResolve(3)}
                  disabled={status === "submitting"}
                  className="w-full bg-blue-600 hover:bg-blue-700 justify-start"
                >
                  <Scale size={16} className="mr-2" /> Split 50/50
                </Button>

                {status === "submitting" && (
                  <div className="flex items-center justify-center gap-2 text-xs text-gray-500 mt-4">
                    <Spinner size="sm" /> Processing resolution...
                  </div>
                )}
              </div>
            )}
          </div>

          <div className="bg-gray-50 border border-gray-200 rounded-xl p-5">
            <div className="flex items-start gap-3">
              <AlertCircle className="text-amber-500 shrink-0" size={18} />
              <div className="text-xs text-gray-600">
                <p className="font-bold mb-1 uppercase">Protocol Rule</p>
                <p>
                  Arbitrators are penalized for inconsistent verdicts. Ensure
                  your decision aligns with the provided evidence and deal
                  terms.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
