export const dealManagerAbi = [
  {
    type: 'function',
    name: 'createDeal',
    inputs: [
      {
        name: 'input',
        type: 'tuple',
        components: [
          { name: 'buyer', type: 'address' },
          { name: 'seller', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'deliveryDeadline', type: 'uint256' },
          { name: 'disputeWindow', type: 'uint256' },
          { name: 'acceptanceWindow', type: 'uint256' },
          { name: 'sellerAcceptanceWindowSecs', type: 'uint256' },
          { name: 'dealType', type: 'uint8' },
          { name: 'partialSettlementAllowed', type: 'bool' },
          { name: 'termsHash', type: 'bytes32' },
          { name: 'metadataHash', type: 'bytes32' },
          { name: 'evidenceRequirementsHash', type: 'bytes32' },
          { name: 'settlementRulesHash', type: 'bytes32' },
          { name: 'verifier', type: 'address' },
          { name: 'disputeResolver', type: 'address' },
        ],
      },
    ],
    outputs: [{ name: 'dealId', type: 'uint256' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'fundDeal',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'acceptDeal',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'rejectDeal',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'cancelDeal',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'expireSellerAcceptance',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getDeal',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [
      {
        name: '',
        type: 'tuple',
        components: [
          { name: 'buyer', type: 'address' },
          { name: 'seller', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'verifier', type: 'address' },
          { name: 'disputeResolver', type: 'address' },
          { name: 'amount', type: 'uint256' },
          { name: 'depositedFunds', type: 'uint256' },
          { name: 'fundingStage', type: 'uint8' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'sellerAcceptanceDeadline', type: 'uint256' },
          { name: 'sellerAcceptedAt', type: 'uint256' },
          { name: 'fundedAt', type: 'uint256' },
          { name: 'deliverySubmittedAt', type: 'uint256' },
          { name: 'deliveryVerifiedAt', type: 'uint256' },
          { name: 'acceptedAt', type: 'uint256' },
          { name: 'finalizedAt', type: 'uint256' },
          { name: 'deliveryDeadline', type: 'uint256' },
          { name: 'acceptanceWindowEndsAt', type: 'uint256' },
          { name: 'disputeWindowEndsAt', type: 'uint256' },
          { name: 'acceptanceWindow', type: 'uint256' },
          { name: 'disputeWindow', type: 'uint256' },
          { name: 'sellerAcceptanceWindowSecs', type: 'uint256' },
          { name: 'dealType', type: 'uint8' },
          { name: 'state', type: 'uint8' },
          { name: 'partialSettlementAllowed', type: 'bool' },
          { name: 'termsHash', type: 'bytes32' },
          { name: 'metadataHash', type: 'bytes32' },
          { name: 'evidenceRequirementsHash', type: 'bytes32' },
          { name: 'settlementRulesHash', type: 'bytes32' },
          { name: 'proofHash', type: 'bytes32' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getDealState',
    inputs: [{ name: 'dealId', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint8' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'dealCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'DealCreated',
    inputs: [
      { name: 'dealId', type: 'uint256', indexed: true },
      { name: 'buyer', type: 'address', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
      { name: 'token', type: 'address', indexed: false },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DealFunded',
    inputs: [
      { name: 'dealId', type: 'uint256', indexed: true },
      { name: 'funder', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'DealAccepted',
    inputs: [
      { name: 'dealId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'DealRejected',
    inputs: [
      { name: 'dealId', type: 'uint256', indexed: true },
      { name: 'seller', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'DealCancelled',
    inputs: [
      { name: 'dealId', type: 'uint256', indexed: true },
      { name: 'canceller', type: 'address', indexed: true },
    ],
  },
] as const;
