export const disputeManagerAbi = [
  {
    type: "function",
    name: "raiseDispute",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "reasonHash", type: "bytes32" },
      { name: "evidenceHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelDispute",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolveDispute",
    inputs: [
      { name: "dealId", type: "uint256" },
      { name: "outcome", type: "uint8" },
      { name: "sellerBps", type: "uint256" },
      { name: "buyerBps", type: "uint256" },
      { name: "resolutionHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getDispute",
    inputs: [{ name: "dealId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "dealId", type: "uint256" },
          { name: "buyer", type: "address" },
          { name: "seller", type: "address" },
          { name: "token", type: "address" },
          { name: "resolver", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "openedAt", type: "uint256" },
          { name: "resolvedAt", type: "uint256" },
          { name: "outcome", type: "uint8" },
          { name: "active", type: "bool" },
          { name: "reasonHash", type: "bytes32" },
          { name: "evidenceHash", type: "bytes32" },
          { name: "resolutionHash", type: "bytes32" },
          { name: "proofHash", type: "bytes32" },
          { name: "termsHash", type: "bytes32" },
          { name: "sellerAward", type: "uint256" },
          { name: "buyerAward", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      { name: "dealId", type: "uint256", indexed: true },
      { name: "raiser", type: "address", indexed: true },
      { name: "reasonHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DisputeResolved",
    inputs: [
      { name: "dealId", type: "uint256", indexed: true },
      { name: "resolver", type: "address", indexed: true },
      { name: "outcome", type: "uint8", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DisputeCancelled",
    inputs: [
      { name: "dealId", type: "uint256", indexed: true },
      { name: "canceller", type: "address", indexed: true },
    ],
  },
] as const;
